const Category = Object.freeze({
  WAR_BATTLE: 'WAR_BATTLE',
  POLITICS: 'POLITICS',
  SCIENCE_INNOVATION: 'SCIENCE_INNOVATION',
  CULTURE_ART: 'CULTURE_ART',
  DISASTER: 'DISASTER',
  FAMOUS_BIRTH_DEATH: 'FAMOUS_BIRTH_DEATH',
  UNKNOWN: 'UNKNOWN'
});

module.exports = Category;
